version: "3.9"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres
    container_name: survey_postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: ozgurpir
      POSTGRES_PASSWORD: 141623
      POSTGRES_DB: survey_app_development
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_data: